
/* Create user */
CREATE USER 'hallondisp'@'%' IDENTIFIED BY 'hallondisp';
GRANT USAGE ON *.* TO 'hallondisp'@'%';
GRANT EXECUTE, SELECT, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `hallondisp`.* TO 'hallondisp'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SHOW GRANTS FOR 'hallondisp'@'%';
